# -*- coding: utf-8 -*-
"""
Created on Tue Jan 26

@author: Miquel Quetglas
"""
#Enviroment.
ENTORNO = 'PRO'

#VIEWS Connection String
#PRE
OPENDATA_CONEXION_BD_PRE="(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1523))(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1523))(CONNECT_DATA=(SERVICE_NAME=xxx)))"
#DES
OPENDATA_CONEXION_BD_DES="(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1523))(CONNECT_DATA=(SERVICE_NAME=xxx)))"
#PRO
OPENDATA_CONEXION_BD="(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1523))(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1523))(CONNECT_DATA=(SERVICE_NAME=xxx)))"

#ORACLE Connection String  

if ENTORNO == 'DES':
	AST1_CONEXION_BD="(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1523))(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1523))(CONNECT_DATA=(SERVICE_NAME=xxx)))"
	AST2_CONEXION_BD="(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=47034)))(CONNECT_DATA=(SERVER = DEDICATED)(SERVICE_NAME = xxx)))"
	AST_TURISMO="(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = xxx)(PORT = 47034)))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = xxx)))"
	ORACLE_IAA="(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = xxx)(PORT = 47034)))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = xxx)))"
	ORACLE_DESFOR_CONEXION="(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = xxx)(PORT = 47034)))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = xxx)))"
elif ENTORNO == 'PRE': 
	AST1_CONEXION_BD="(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1523))(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1523))(CONNECT_DATA=(SERVICE_NAME=xxx)))"
	AST2_CONEXION_BD="(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=47034)))(CONNECT_DATA=(SERVER = DEDICATED)(SERVICE_NAME = xxx)))"
	AST_TURISMO="(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = xxx)(PORT = 47034)))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = xxx)))"
	ORACLE_IAA="(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = xxx)(PORT = 47034)))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = xxx)))"
	ORACLE_IAA_VIEJAS="(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=xxx)))"
	ORACLE_DESFOR_CONEXION="(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = xxx)(PORT = 47034)))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = xxx)))"
elif ENTORNO == 'PRO':
	AST1_CONEXION_BD="(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1523))(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1523))(CONNECT_DATA=(SERVICE_NAME=xxx)))"
	AST2_CONEXION_BD="(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=47017)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=xxx)))"
	AST_TURISMO="(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = xxx)(PORT = 47017)))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = xxx)))"
	ORACLE_IAA="(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = xxx)(PORT = 47017)))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = xxx)))"
	ORACLE_IAA_VIEJAS="(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=xxx)))"
	ORACLE_DESFOR_CONEXION="(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = xxx)(PORT = 47017)))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = xxx)))"
	ENERGIA="(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1523))(CONNECT_DATA=(SERVICE_NAME=xxx)))"
	ORACLE_ADMIN_ELECTRONICA_CONEXION="(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = xxx)(PORT = 47017)))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = xxx)))"
	BIBLIOTECAS_BD="(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = xxx)(PORT = 47017)))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = xxx)))"

CRA_CONEXION="(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(Port=1521)))(CONNECT_DATA=(SID=orac)))"
CRA_USR="xxx"
CRA_PASS="xxx"

#POSTGRESQL Connection String
AST3_CONEXION_BD = "host='xxx' dbname='xxx' port='xxx' user='xxx' password='xxx'"
OPENDATA_POSTGRE_CONEXION_BD="host='xxx' dbname='xxx'  port='xxx' user='xxx' password='xxx'"
PRESUPUESTOS_POSTGRE_CONEXION_BD="host='xxx' dbname='xxx'  port='xxx' user='xxx' password='xxx$t0s'"
DOMINIOS_POSTGRE_CONEXION_BD="host='xxx' dbname='xxx'  port='xxx' user='xxx' password='xxx$'"
EMPLEO_PUBLICO_CONEXION_BD="host='xxx' dbname='xxx' port='xxx' user='xxx' password='xxx'"

#IGEAR
IGEAR_CONEXION_BD = "host='xxx' dbname='xxx' port='xxx' user='xxx' password='xxx'"

#SALUD
SALUD_CONEXION_BD = "host='xxx' dbname='xxx' port='xxx' user='xxx' password='xxx'"

#SQL_SERVER Connection String
AST4_CONEXION_BD = "host='bov-domus-01.aragon.local', user='OPENDATA_USR', password='xxx', database='xxx'"

#ORACLE_IAA_VIEJAS="(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=xxx)))"

#Transportes Connectio String
TRANSPORTE_CONEXION="(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = xxx)(PORT = 1521)))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = xxx)))"

#Users
OPENDATA_USR="xxx"
OPENDATA_PASS="xxx"
OPENDATA_PASS_PRO="xxx$"
OPENDATA="xxx"
AST_USR="xxx"
AST_PASS="xxx"
USR_ADMIN="xxx"
ORACLE_IAA_USR="xxx"
ORACLE_IAA_PASS="xxx"
#Table or View with the list of Views
OPEN_VIEWS="OPENDATA.OPENDATA_V_VISTAS"
ORACLE_DESFOR_USR="xxx"
ORACLE_DESFOR_PASS="xxx"

#Aplication path
APP_PATH="/data/apps/py_virtualenv_36/GA_OD_Core"

#Custom log of the aplication
CUSTOM_LOG="/data/apps/py_virtualenv_36/GA_OD_Core/ga_od_core_custom.log"

#Number of records returned by the function "preview_vista"
NUM_REGISTROS=5000

#Debuf functions and DB depends of the enviroment.
if ENTORNO == 'DES':
    VIEWS_DB = 'des-opendata-oracle'
    DEBUG_VAR = True
elif ENTORNO == 'PRE':
    VIEWS_DB = 'pre-opendata-oracle'
    DEBUG_VAR = True
elif ENTORNO == 'PRO':
    VIEWS_DB = 'pro-opendata-oracle'
    DEBUG_VAR = True

#For google analytics
SERVICE_ACCOUNT_EMAIL='cuentadeservicio1@commanding-bee-129211.iam.gserviceaccount.com'
